deployment:
  name: tomcat-deploy-project
  replicaCount: 1
image:
  repository: jivedh2019/assign
  tag: IMAGE_TAG
  containerPort: 8080
service:
  type: NodePort
  clusterIPPort: 8080
  nodePort: 30000
namespace: prod
