deployment:
  name: tomcat-deploy-project
  replicaCount: 1
image:
  repository: fatimatabassum/fatima12
  tag: IMAGE_TAG
  containerPort: 8080
service:
  type: ClusterIP
  clusterIPPort: 3000
namespace: dev
